### ISSUE TITLE
flatpak-node-generator cannot resolve correctly some Node dependencies

### ISSUE THREAD

**Issue by x80486** [flatpak/flatpak-builder-tools#110]
I don't know if it is possible to correct this on your side, but I've been trying to Flatpak `Standard Notes` using the `flatpak-node-generator`. Previously I had an issue with a similar dependency (`spellchecker`...gone for good!) and now it's `standard-notes-web`: https://github.com/standardnotes/desktop/blob/v3.4.0-beta1/app/package.json#L15

So I was wondering if there is a way for `flatpak-node-generator` to correctly resolve those type of dependencies, or if there is a workaround available; currently the `generated-sources.json` output file has something like this:

```json
    {
        "type": "file",
        "url": "https://codeload.github.com/standardnotes/web/tar.gz/b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6",
        "sha256": "397e93f6dc4978f9d67b9421a833943bbe4e9474fa5e1c65294ab3d0dbe4665a",
        "dest-filename": "standard-notes-web-3.3.5",
        "dest": "flatpak-node/yarn-mirror"
    },
    {
        "type": "file",
        "url": "https://registry.yarnpkg.com/@marshallofsound/enjoi-browser/-/enjoi-browser-1.0.5.tgz#00507c6fb3ee6a032aa45bb4da8d78624b6fec16",
        "sha512": "940678aba0cfaa84af0a6f1fcfe031ba7645848b7918baa78395c874bbd33557be22e4ec17772685aae96db4b5880049f5c8989d82dfe77f620ba2173e50102d",
        "dest-filename": "@marshallofsound-enjoi-browser-1.0.5.tgz",
        "dest": "flatpak-node/yarn-mirror"
    },
   ...
```

**Comment by refi64** [comment]
What about the dependency isn't resolved correctly? The yarn code mostly just takes the data straight from yarn.lock, no crazy magic / mess like npm needs.

**Comment by x80486** [comment]
What do you mean by "the dependency isn't resolved correctly"?

I just go by the assumption that the way it's declared works somehow: `"standard-notes-web": "github:standardnotes/web#b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6"`

That gets "translated" in the Yarn lock file as:

```yarn
"standard-notes-web@github:standardnotes/web#b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6":
  version "3.3.5"
  resolved "https://codeload.github.com/standardnotes/web/tar.gz/b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6"
  dependencies:
    lodash "^4.17.15"
```

...but looks like it has to be in this format to work:

```yarn
sprintf-js@~1.0.2:
  version "1.0.3"
  resolved "https://registry.yarnpkg.com/sprintf-js/-/sprintf-js-1.0.3.tgz#04e6926f662895354f3dd015203633b857297e2c"
  integrity sha1-BOaSb2YolTVPPdAVIDYzuFcpfiw=
```

I don't know if there is another way to circumvent this. Let me go to their side and ask if they can declare that dependency in a different way, like the other dependencies.

**Comment by refi64** [comment]
That's not a resolving issue... The dependency is from GitHub, so Yarn
downloads it from GitHub instead of the registry. Was there any particular
behavior being exhibited that led you to believe it wasn't being resolved
correctly?

**Comment by x80486** [comment]
I'm getting the typical:

```shell
warning standard-notes@3.3.5: No license field
error An unexpected error occurred: "https://codeload.github.com/standardnotes/web/tar.gz/b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6: getaddrinfo EAI_AGAIN codeload.github.com".
```

This is the complete output log: https://8n1.org/17114/c9fa (from this repo: https://github.com/x80486/flathub/tree/org.standardnotes.standardnotes)

**Comment by gasinvein** [comment]
Hm, maybe `dest-filename` should be `b075d1b7fb66d0f6235a72f4faa41cb2f2b3b5c6` instead of `standard-notes-web-3.3.5`?

**Comment by refi64** [comment]
Ah I see, I think it's missing the tar.gz file extension.

**Comment by x80486** [comment]
Huh :hushed: ...it built fine as soon as that's changed! :partying_face: :balloon: :partying_face: :balloon:  ...thank you so much, Filippe!

**Comment by gasinvein** [comment]
@refi64 You mean `standard-notes-web-3.3.5.tar.gz` should work as well?

**Comment by refi64** [comment]
@gasinvein sorry nope, I'm just an idiot. This is fixed locally and will be uploaded later today.
