### ISSUE TITLE
[pip] add yaml support

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak-builder-tools#114]
It is also possible to write flatpak manifests in yaml language.

It can be useful to add an option to flatpak-pip-generator such as `--yaml` in order to produce manifests in this format.

**Comment by refi64** [comment]
pip-generator just generates the sources file that you include in your main
manifest, i.e. you can have a YAML manifest and still use the generated
JSON file.

**Comment by roipoussiere** [comment]
I personally prefer to copy-paste the content in my flatpak manifest in order to have a single file. :)

**Comment by barthalion** [comment]
This is on purpose. JSON is for machine-generated files. You can trivially convert it to YAML if you like, I think a tool for this is included in the repo.
