### ISSUE TITLE
[pip] possibility to chose checksum algorithm

### ISSUE THREAD

**Issue by roipoussiere** [flatpak/flatpak-builder-tools#115]
flatpak-builder-tools adds modules with sha256 checksums in flatpak manifests.

flatpak-builder supports many others: `md5`, `sha1`, `sha256`, and `sha512`.

Some users may have a preference and appreciates the possibility to chose a specific one, for instance with a `--checksum_type=CHECKSUM_TYPE` option.

**Comment by TingPing** [comment]
I'll be honest this is just a waste of time sha256 is entirely acceptable for the purposes of just verifying a file was not corrupted.
