### ISSUE TITLE
[pip] NameError: name 'x' is not defined

### ISSUE THREAD

**Issue by ghisvail** [flatpak/flatpak-builder-tools#117]
When [this line](https://github.com/flatpak/flatpak-builder-tools/blob/0e55933dc173be83c89344a588041d1037b6a52f/pip/flatpak-pip-generator#L103) gets hit. I suspect this code path has never been verified properly.

I was able to test it with a `requirements.txt` file containing a comment.

**Comment by joshua-stone** [comment]
I've also run into this bug when using [requirements.txt](https://github.com/sabnzbd/sabnzbd/blob/develop/requirements.txt) files that have comment lines in them.

The workaround I've used is to delete the comment lines.

**Comment by A6GibKm** [comment]
Fixed by #132.
