### ISSUE TITLE
[pip] flatpak-pip-generator not working for tensorflow

### ISSUE THREAD

**Issue by denn-s** [flatpak/flatpak-builder-tools#125]
Flatpak-pip-generator can not be used for tensorflow. Process fails with the following log messages:
```
Successfully downloaded tensorflow scipy astunparse termcolor wrapt h5py keras-preprocessing grpcio numpy protobuf absl-py gast opt-einsum tensorboard six wheel google-pasta tensorflow-estimator setuptools google-auth-oauthlib requests markdown google-auth tensorboard-plugin-wit werkzeug requests-oauthlib chardet idna urllib3 certifi cachetools pyasn1-modules rsa oauthlib pyasn1
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
Failed to download tensorflow
Please fix the module manually in the generated file
```

The error can be reproduced in the following way:
`python3 flatpak-pip-generator.py tensorflow`

operating system: Ubuntu 20.04 
pip version: 20.1.1
python version: 3.8.2

The output file being generated:
``` json
{
    "name": "python3-tensorflow",
    "buildsystem": "simple",
    "build-commands": [
        "pip3 install --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} tensorflow"
    ],
    "sources": []
}
```

**Comment by TingPing** [comment]
They don't seem to have any source releases: https://pypi.org/project/tensorflow/#files

**Comment by denn-s** [comment]
You are right, I did not think about that. So this is not an issue with the flatpak-pip-generator script. Then i am going to skip the idea of creating an gtk + tensorflow application for now. Thank you for your work on this project.
