### ISSUE TITLE
[pip] `TypeError: sequence item 6: expected str instance, NoneType found` with Git dependencies

### ISSUE THREAD

**Issue by strugee** [flatpak/flatpak-builder-tools#134]
9a12506a9d384770dd40b333967b53afc0762ae2 / #132 appears to introduce a regression in the way that Git dependencies are handled (although it's unclear to me if this is a regression or simply a different bug due to #133). STR:

```
$ pwd
/home/alex/Development/flatpak-pip-bug/flatpak-builder-tools/pip

$ cat requirements.txt
git+git://github.com/Amulet-Team/Amulet-Core.git@4986e49c143abded07e548b486d71c5085a77d41

$ ./flatpak-pip-generator --requirements-file=requirements.txt
Traceback (most recent call last):
  File "./flatpak-pip-generator", line 133, in <module>
    ('build-commands', [' '.join(pip_command)]),
TypeError: sequence item 6: expected str instance, NoneType found

$ git rev-parse HEAD
f781c10d5e06c968c108516ea27ceee769dab8a5
```

I inserted a `breakpoint()`  on line 108 (right after `for package in packages:`):

```
$ ./flatpak-pip-generator --requirements-file=requirements.txt
> /home/alex/Development/flatpak-pip-bug/flatpak-builder-tools/pip/flatpak-pip-generator(109)<module>()
-> package_name = 'python{}-{}'.format(python_version, package.name)
(Pdb) interact
*interactive*
>>> package
<Requirement: "git+git://github.com/Amulet-Team/Amulet-Core.git@4986e49c143abded07e548b486d71c5085a77d41">
>>> package.name
>>> type(package.name)
<class 'NoneType'>
>>> 
```

So that seems to be where the problem is coming from. Here's the same thing on a non-Git dependency:

```
$ cat requirements-nongit.txt 
requests

$ ./flatpak-pip-generator --requirements-file=requirements-nongit.txt
> /home/alex/Development/flatpak-pip-bug/flatpak-builder-tools/pip/flatpak-pip-generator(109)<module>()
-> package_name = 'python{}-{}'.format(python_version, package.name)
(Pdb) interact
*interactive*
>>> package
<Requirement: "requests">
>>> package.name
'requests'
>>> 
```

/cc @A6GibKm @TingPing either of you have any idea why this is happening? I'm relatively new to Python packaging.

**Comment by A6GibKm** [comment]
Could you share the requirements.txt file? Have in mind that the git feature wasn't working before.

**Comment by A6GibKm** [comment]
I will look into it, not that the git feature wasn't working before either.

**Comment by strugee** [comment]
@A6GibKm phenomenal timing :joy: I just nailed down the issue.

Looks like the problem is that the version specification doesn't include the [required](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) `#egg=<pkgname>` suffix. The parser doesn't enforce this though so we get `None` as the package name. (FWIW I _did_ include the original `requirements.txt` file contents; it's in that first code block in the issue description. In retrospect it probably could've been easier to find though, sorry!)

I'll prepare a patch that warns about this case and tells the user how to fix it.

**Comment by A6GibKm** [comment]
Yup, got to the same conclusion.  Want to take care about this? There are two options:

* Warn the user that `#egg` is missing
* Do a special case for `name == None`

In any case the output won't work in `flatpak-builder` as pip doesn't know how to install from a git source using the same formula.

**Comment by strugee** [comment]
Right, makes sense. I ran into this while trying to package an existing application so initially it didn't even occur to me that the requirement specifications might be invalid since I'm not used to pip. I'll be sending patches upstream to fix that :)

**Comment by A6GibKm** [comment]
@TingPing since the error is that `git+git://github.com/Amulet-Team/Amulet-Core.git@4986e49c143abded07e548b486d71c5085a77d41` is not following the [format](https://pip.pypa.io/en/stable/user_guide/#requirements-files), should we do something about this?

One possibility is to add
```python
                # Throw an error if `#egg=name` is missing.
                if not package.name:
                    url = 'https://pip.pypa.io/en/stable/user_guide/#requirements-files'
                    print('{} is invalid, see {}'.format(opts.requirements_file, url))
                    exit()
```
The other is to do nothing since the file was ill-formated.

**Comment by strugee** [comment]
Filed #136 to fix this.
