### ISSUE TITLE
pip: ModuleNotFoundError: No module named 'requirements'

### ISSUE THREAD

**Issue by sumnerevans** [flatpak/flatpak-builder-tools#140]
When I run the following commands:
```
$ git clone https://github.com/flatpak/flatpak-builder-tools.git
$ python3 ./flatpak-builder-tools/pip/flatpak-pip-generator --requirements-file=flatpak-requirements.txt --output pypi-dependencies
```

I get this error:
```
Traceback (most recent call last):
  File "./flatpak-builder-tools/pip/flatpak-pip-generator", line 9, in <module>
    import requirements
ModuleNotFoundError: No module named 'requirements'
```
on the latest commit to `master`. This seems to have started at 9a12506 because I do not have the same issue if I use 8dd64fc. However, when I go one commit up to 9a12506, this error starts happening.

**Comment by TingPing** [comment]
`pip3 install --user requirements-parser`.

Maybe it should be optional @A6GibKm

**Comment by A6GibKm** [comment]
It is possible to detect if a python module is installed? The optimal would be to use `requirements-parser` when available and fallback to `readlines()` otherwise.

**Comment by TingPing** [comment]
Changed by 3b460d29d6c58eabdccce2595faa2d512fa0259d
