### ISSUE TITLE
[cargo] Workspace members with globs not supported

### ISSUE THREAD

**Issue by JMS55** [flatpak/flatpak-builder-tools#148]
The following breaks:
```toml
[workspace]
members = [
    "examples/*",
    "internals/*",
]
```

**Comment by gasinvein** [comment]
Can you please provide an example of package with such workspace and an app depending on it?

**Comment by JMS55** [comment]
Pixels uses a workspace like this https://github.com/parasyte/pixels
My game Sandbox uses pixels https://github.com/JMS55/sandbox
`flatpak-cargo-generator.py ./Cargo.lock -o ./flatpak/crate-sources.json`

**Comment by JMS55** [comment]
Yep it works, thanks!
