### ISSUE TITLE
flatpak-pip-generator: unexpected behaviour for packages that rely on wheel

### ISSUE THREAD

**Issue by Hofer-Julian** [flatpak/flatpak-builder-tools#157]
The flatpak-pip-generator produces incomplete json modules for packages that rely on wheel (not packaged as wheels, but list it as dependency).

**Steps to reproduce:**
Run
```
python flatpak-pip-generator.py debugpy
```
this outputs a file like this:
```json
{
    "name": "python3-debugpy",
    "buildsystem": "simple",
    "build-commands": [
        "pip3 install --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} \"debugpy\""
    ],
    "sources": [
        {
            "type": "file",
            "url": "https://files.pythonhosted.org/packages/92/78/6f8857235b6b67194af3e66d0767d102e32a3e4055d0212f1783c0b4e5b0/debugpy-1.1.0.zip",
            "sha256": "955af25acd01ddd6a7adf6e495b118ed2adf072c61294a7e899c2c32f64e9a60"
        }
    ]
}
```
Adding this in a flatpak manifest fails with "ERROR: Could not find a version that satisfies the requirement wheel". Adding a module with "wheel" in front of it does not help. The only thing that works is adding "wheel" and "setuptools" sources to the module like this:
```json
{
      "name": "python3-debugpy",
      "buildsystem": "simple",
      "build-commands": [
        "pip3 install --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST}  \"debugpy\""
      ],
      "sources": [
        {
          "type": "file",
          "url": "https://files.pythonhosted.org/packages/92/78/6f8857235b6b67194af3e66d0767d102e32a3e4055d0212f1783c0b4e5b0/debugpy-1.1.0.zip",
          "sha256": "955af25acd01ddd6a7adf6e495b118ed2adf072c61294a7e899c2c32f64e9a60"
        },
        {
          "type": "file",
          "url": "https://files.pythonhosted.org/packages/a7/00/3df031b3ecd5444d572141321537080b40c1c25e1caa3d86cdd12e5e919c/wheel-0.35.1-py2.py3-none-any.whl",
          "sha256": "497add53525d16c173c2c1c733b8f655510e909ea78cc0e29d374243544b77a2"
        },
        {
          "type": "file",
          "url": "https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl",
          "sha256": "2c242a0856fbad7efbe560df4a7add9324f340cf48df43651e9604924466794a"
        }
      ]
    }
```

**Comment by gasinvein** [comment]
Maybe @nanonyme has an idea why pip even wants `wheel` and `setuptools` wheels while this modues are already available in the SDK?

**Comment by muelli** [comment]
I think I experienced similar behaviour when running the generator in an environment that has wheels installed, i.e. my "normal" Python environment rather than a dedicated nearly empty virtualenv. But my memory may serve me wrongly.

**Comment by nanonyme** [comment]
Sorry, really busy. --no-build-isolation or something as parameter to pip. See help

**Comment by Hofer-Julian** [comment]
Thanks @nanonyme, that indeed worked.
Reading the help (see below), it seems to me as if we could just pass this flag to every module.
Would you agree with that statement?
```
--no-build-isolation        Disable isolation when building a modern source
                              distribution. Build dependencies specified by
                              PEP 518 must be already installed if this option
                              is used.
```

**Comment by gasinvein** [comment]
@Hofer-Julian while it seems like a good idea to me (since we have consistent python environment inside the flatpak sandbox anyway), I'm not sure if it'll work for _all_ modules, especially the ones that have build dependencies other than wheel and setuptools. We'll need to check this out.

**Comment by Hofer-Julian** [comment]
Good point, I guess the best we can do is to try as many as possible and adjust the script according to our findings

**Comment by nanonyme** [comment]
It should work for everything. Freedesktop-sdk uses that internally.

**Comment by gasinvein** [comment]
Ok, so the generator seems to already have the `--no-build-isolation` options which it passes to `pip`. I wonder why I never noticed that.
https://github.com/flatpak/flatpak-builder-tools/blob/87aa7449e2b190ca3457ec77581a65ffffac8f79/pip/flatpak-pip-generator#L33-L34
https://github.com/flatpak/flatpak-builder-tools/blob/87aa7449e2b190ca3457ec77581a65ffffac8f79/pip/flatpak-pip-generator#L362-L363
@Hofer-Julian Does it work for you?

**Comment by Hofer-Julian** [comment]
Yes, it does.
I only tested it on this one module though 😊

**Comment by nanonyme** [comment]
Maybe the default should be changed now that there's new pip more commonly available. Build isolation works poorly if pip can't download missing dependencies.

**Comment by nanonyme** [comment]
Alternatively we should structurally change this so we stage all sources together (also setuptools and wheel just to be on safe side) and tell pip to do its stuff based on our local collection of packages.

**Comment by Hofer-Julian** [comment]
> Ok, so the generator seems to already have the `--no-build-isolation` option which it passes to `pip`. I wonder why I never noticed that.
> 
> https://github.com/flatpak/flatpak-builder-tools/blob/87aa7449e2b190ca3457ec77581a65ffffac8f79/pip/flatpak-pip-generator#L33-L34
> 
> https://github.com/flatpak/flatpak-builder-tools/blob/87aa7449e2b190ca3457ec77581a65ffffac8f79/pip/flatpak-pip-generator#L362-L363
> 
> @Hofer-Julian Does it work for you?

Just checked the version of the script and it seems like the type of the argument has been forgotten, now it expects a string input while it should of course be a boolean switch

**Comment by Hofer-Julian** [comment]
> Alternatively we should structurally change this so we stage all sources together (also setuptools and wheel just to be on safe side) and tell pip to do its stuff based on our local collection of packages.

What benefit do you see with this solution?
The benefit I see with the current proposal (just making no-build-isolation default) is that we can just have modules with empty sources for packages that fail. You can see here that these are quite a lot (https://github.com/flatpak/flatpak-builder-tools/issues?q=is%3Aissue+is%3Aopen+pip). These sources can then be added manually. This would be harder to do with a single module.

**Comment by HelpSeeker** [comment]
It might be a good idea to mention this issue in the corresponding readme, until you come up with a final solution.
