### ISSUE TITLE
Compiling results into "cannot find -lstdc++fs" ?

### ISSUE THREAD

**Issue by llothar** [flatpak/flatpak-builder-tools#171]
How do i get this fixed?  

Also how can i pass VERBOSE=1 to the make invocation to get a better more informative output, I really hate this 

`[24%] Building foobar.cpp`

messages  from modern gmake when something goes wrong.

PS: We need a special community discussion tool for the flatpak-builder.

**Comment by gasinvein** [comment]
This has nothing to do with flatpak-builder-tools, and I guess with flatpak-builder either.

Freedesktop-SDK doesn't provide separate `libstdc++fs` library and apps aren't supposed to link with it explicitly. If I remember correctly, `std::filesystem` functions were included in `libstdc++` in GCC 9, so probably removing the `-lstdc++fs` linker flag would be sufficient.

**Comment by hfiguiere** [comment]
I have a few package that I patch this out because their built system just assert there is `libstdc++fs`. (they only tested Ubuntu)

I don't think it's an issue with the tools.
