### ISSUE TITLE
[node] Electron >= 7.0.0 fails to build

### ISSUE THREAD

**Issue by roypen** [flatpak/flatpak-builder-tools#177]
Hi,

I'm trying to build flatpak of "geforcenow electron" [app](https://github.com/hmlendea/geforcenow-electron). As a template I'm using 'vanilla-quick-start'. The "gerorcenow" app uses Electron 11.0.2, which fails to build. I've tested different solutions, and I've noticed that when I use every version of Electron higher or equal to 7.0.0 the flatpak build process fails and returns always the same error:
```
> electron@7.0.0 postinstall /run/build/electron-geforcenow/electron-geforcenow/node_modules/electron
> node install.js
(node:20) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo EAI_AGAIN github.com
RequestError: getaddrinfo EAI_AGAIN github.com
    at ClientRequest.<anonymous> (/run/build/electron-geforcenow/electron-geforcenow/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/run/build/electron-geforcenow/electron-geforcenow/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.4.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@9.4.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Electron version 6.0.0 (or lower) builds without any error. Since Electron 7.0.0, the `request` module has been "replaced" by `got` module, as described here [#3142](https://github.com/request/request/issues/3142) and here [#3143](https://github.com/request/request/issues/3143). It looks like `got` module, and its dependences are causing problems with proper flatpak build. Probably the module is trying to access the internet. I'm using Freedesktop 20.08, Electron2.BaseApp and node14, Fedora 33. I will appreciate any help.

Here is my manifest file: 
[org.electron.geforcenow.yaml](https://github.com/roypen/geforcenow-electron/blob/Flatpak/org.electron.geforcenow.yaml)
I'm aware that even if I manage to build this electron app, I will have trouble running it in the sandbox.

**Comment by gasinvein** [comment]
Try using `--xdg-layout` option, similarly to [this](https://github.com/flatpak/flatpak-builder-tools/issues/173#issuecomment-741989549).

**Comment by roypen** [comment]
Thanks! It works. Another milestone reached ;)

**Comment by roypen** [comment]
the issue has been resolved. thanks!
