### ISSUE TITLE
[node] Support https scheme in git urls

### ISSUE THREAD

**Issue by gasinvein** [flatpak/flatpak-builder-tools#185]
Yarn lockfiles can have entries with git urls without any special scheme like `git+https`, just `https`, like this:
```yarn
"emmet@https://github.com/rzhao271/emmet.git#1b2df677d8925ef5ea6da9df8845968403979a0a":
  version "2.3.0"
  resolved "https://github.com/rzhao271/emmet.git#1b2df677d8925ef5ea6da9df8845968403979a0a"
  dependencies:
    "@emmetio/abbreviation" "^2.2.0"
    "@emmetio/css-abbreviation" "^2.1.2"
```
@refi64 I'm not sure how to approach this better, i.e. how we can reliably distinguish git sources from normal packages?

**Comment by refi64** [comment]
Is this on Yarn 1.x? If so, there seem to be some regexes in the source used to detect it: https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/resolvers/exotics/git-resolver.js#L17

I might try fixing this soon, my todo list is eternally long but I've had planned for the node generator for a while now..

**Comment by gasinvein** [comment]
A-ha. Should we use this regexps to detect git instead of just looking into url scheme, then? Seem rather easy to implement.
