### ISSUE TITLE
flatpak-pip-generator: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Alexander-Wilms** [flatpak/flatpak-builder-tools#190]
The following error does not occur with https://github.com/flatpak/flatpak-builder-tools/commit/1716a745442ae3f1e1f45ba8485713d4cc5d26ae#diff-f8067100be2ca0010ec23a52f060b978ffe434f795bb851ec330c30e3e8921b0, only https://github.com/flatpak/flatpak-builder-tools/commit/ff583c6d8364cbd431e0b14bf3f432962fcd8757#diff-f8067100be2ca0010ec23a52f060b978ffe434f795bb851ec330c30e3e8921b0

```
./flatpak-pip-generator mpmath sympy
  File "/home/awilms/Development/flatpak-builder-tools/pip/./flatpak-pip-generator", line 40
    parser.add_argument('--output', '-o',
    ^
SyntaxError: invalid syntax
```

**Comment by gasinvein** [comment]
Meeh, looks like a closing parentheses after arg is missing.

**Comment by Alexander-Wilms** [comment]
Thanks

**Comment by gasinvein** [comment]
Thanks for reporting this.
