### ISSUE TITLE
[Node] support lockfile version 2

### ISSUE THREAD

**Issue by proletarius101** [flatpak/flatpak-builder-tools#192]
According to https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json/#lockfileversion

> Lockfiles generated by npm v7 will contain lockfileVersion: 2.
> 1: The lockfile version used by npm v5 and v6.
> 2: The lockfile version used by npm v7, which is backwards compatible to v1 lockfiles.
> 3: The lockfile version used by npm v7, without backwards compatibility affordances. This is used for the hidden lockfile at node_modules/.package-lock.json, and will likely be used in a future version of npm, once support for npm v6 is no longer relevant.

So basciallly lockfile version 2 is backwards compatible to v1 lockfiles which is already supported by `flatpak-builder-tools`. So I guess a simple change from 
https://github.com/catsout/flatpak-builder-tools/blob/46945dc49fa37d7d4381aea14588d88b070665bf/node/flatpak-node-generator.py#L1016
````python
        assert data['lockfileVersion'] == 1, data['lockfileVersion']
````

to

````python
        assert data['lockfileVersion'] == 1 or data['lockfileVersion'] == 2, data['lockfileVersion']
````

is enough?

**Comment by refi64** [comment]
It seems like it, v2 adds a [new field?](https://nitayneeman.com/posts/catching-up-with-package-lockfile-changes-in-npm-v7/) so we can just ignore that I think like we already are.

**Comment by tinywrkb** [comment]
I'm hitting this issue while trying to package [pslab-desktop](https://github.com/fossasia/pslab-desktop).  
Except for the `lockfileVersion` value, `flatpak-node-generator.py` process the lock file correctly.
