### ISSUE TITLE
some package.json provide github commits or tags

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak-builder-tools#2]
As I said, some of npm's package.json have git urls as dependancies. These urls are not converted to sources. [Here is a example](https://github.com/jitsi/jitsi-meet/blob/master/package-lock.json#L6388). After parsing this file, the generated json doesn't have this (there are more such git urls in above json, they are also not generated).

**Comment by nedrichards** [comment]
is this true for package-lock.json files and yarn.lock files? or just the base package.json?

**Comment by adityashah1212** [comment]
It is true even in case of pacakge-lock.json and is pretty variant in it's format. In case of yarn.lock it is a little more consistent

**Comment by alexlarsson** [comment]
Fixed by https://github.com/flatpak/flatpak-builder-tools/pull/3 ?

**Comment by adityashah1212** [comment]
yup closing
