### ISSUE TITLE
[PIP] New dependency format causes build errors

### ISSUE THREAD

**Issue by Eonfge** [flatpak/flatpak-builder-tools#201]
I found that the new dependency format, where packages are build from sources, don't compile in all scenarios. Case in point: Lollypop.

Requirements file from upstream:
https://gitlab.gnome.org/World/lollypop/-/blob/master/requirements.txt

Example build:
https://github.com/flathub/org.gnome.Lollypop/pull/145

**Comment by gasinvein** [comment]
Do you what exact commit changed that, i.e. when the script started to generate `sdist` sources instead of `bdist_wheel`s?

**Comment by Eonfge** [comment]
My guess is here:
https://github.com/flatpak/flatpak-builder-tools/commit/f732068a39b2cbc662dbd271003a7ef87f9d498f

For compiling the list of dependencies now, I actually roll back to this commit:
https://github.com/flatpak/flatpak-builder-tools/commit/167e028582d744fe5721de71baa5ad7ce9e3719e

**Comment by Eonfge** [comment]
So... this is still quite annoying. Anybody gave this a look? @tpikonen Did you notice this while making changes to PIP recently?

**Comment by hfiguiere** [comment]
I have reverted commit f732068 in #238 so if you can retest this solve the issue.

**Comment by Eonfge** [comment]
Can confirm. The reverted change allows me to build a proper `pypi-dependencies.json` again. See https://github.com/flathub/org.gnome.Lollypop/pull/159 for the changes in effect.
