### ISSUE TITLE
[cargo] Fails with git dependencies

### ISSUE THREAD

**Issue by sophie-h** [flatpak/flatpak-builder-tools#207]
```sh
error: failed to get `ashpd` as a dependency of package `pika-backup v0.4.0-alpha (/run/build/pika-backup)`
Caused by:
  failed to load source for dependency `ashpd`
Caused by:
  Unable to update https://github.com/bilelmoussaoui/ashpd.git#5467d7f3
Caused by:
  can't checkout from 'https://github.com/bilelmoussaoui/ashpd.git': you are in the offline mode (--offline)
```

**Comment by gasinvein** [comment]
I'm guessing you're trying to build `org.gnome.World.PikaBackup`.
You use static `cargo-config.toml` there, which doesn't have entries for vendored git sources.
The `flatpak-cargo-generator.py` script generates it's own cargo config file and puts it at `cargo/config` path; usually `cargo` is pointed to this config via `CARGO_HOME` env var.

**Comment by sophie-h** [comment]
Thanks! That fixed it!

How ignorant of me to assume that the generated config wouldn't be of importance :angry:

**Comment by gasinvein** [comment]
Do you need a custom cargo config? I think we can add an option to the script to add the vendored source entries to provided config, instead of creating a new one.

**Comment by sophie-h** [comment]
No, never had the need for that :)
