### ISSUE TITLE
[yarn] Potentially malformed generated source

### ISSUE THREAD

**Issue by ghisvail** [flatpak/flatpak-builder-tools#21]
Same context as in #20.

The corresponding `generated-sources.json` contains the following entry which looks malformed:
```json
{
        "type": "file",
        "url": "data:4497dd6b2f742ce8de3d0fedd5b109dff8abfb9f0c004e2e81ae7f0bf00cf1b0%20%2Aelectron-v1.8.3-linux-ia32.zip%0A0bd8ba049ee63282f00ff25208d77bfb6500fba88181bb919219373557f79515%20%2Aelectron-v1.8.3-linux-x64.zip%0A3e282d3caa1fdff3b97dfa1718e2a9fa4e5658e91b9bdfbbc55a8815c79087ae%20%2Aelectron-v1.8.3-linux-arm.zip%0A",
        "dest": "electron-cache",
        "dest-filename": "SHASUMS256.txt-1.8.3"
}
```

Am I correct?

**Comment by ghisvail** [comment]
@TingPing Btw, this is also happening for the npm helper. Shall I file a different issue for it?

**Comment by TingPing** [comment]
Eh, here is probably fine, same person would likely fix both.

**Comment by muelli** [comment]
does this problem here still exist?
The generator has been around for quite a while now and has served many applications. I wonder whether this nearly four year old report is still relevant.

**Comment by refi64** [comment]
This was for the old yarn generator I think, I doubt anyone is actively using it anymore.
