### ISSUE TITLE
flatpak-pip-generator could be on PyPI

### ISSUE THREAD

**Issue by danielquinn** [flatpak/flatpak-builder-tools#211]
It's really rare to run Python scripts by first pulling them down via wget.  It's even less common to do this when that script has a dependency.  Packaging `flatpak-pip-generator` into a proper package would make it easy for projects to include it as a development dependency and use it more easily.

If there's interest in this, I'm happy to roll something together with Poetry, but the question of ownership of the package on PyPI is always a concern.  It really should be a role account that's published via CI or something rather than any one person having rights to publish to it.

**Comment by TingPing** [comment]
The idea was you can use the tools as a git submodule, but I understand that isn't the most friendly.

I'm ok with turning into a real package. Are you familiar with setting up CI to publish versions? I'd imagine the awkward part is that this repo has many tools in it so tags/releases don't make sense as a trigger.

**Comment by danielquinn** [comment]
I'm familiar with GitLab CI -- I don't really use GitHub anymore myself.  Either way though you're right, it'd be weird to have the package be built via the CI but *not* trigger a publish on commit to `master` or a tag.  My recommendation then would be to break it out into a separate repo, unless that'd be problematic?

**Comment by danielquinn** [comment]
Hmmm.  What you *could* do is make part of the CI run pull down the latest version of the package, check its version against the one listed in the repo and do a push if they're different.  It's **ugly**, but it could work if you're resistant to breaking this out as a `flatpak-builder-python-tools` repo or something equivalent.

**Comment by TingPing** [comment]
I think its worth trying to keep here. Easier shared maintenance.

**Comment by danielquinn** [comment]
Alright then, no problem.  I tried to use it anyway and it failed to generate the required JSON for my project so I won't be using it anyway.  I've written [this build script](https://gitlab.com/-/snippets/2149903) for what it's worth if you guys wanna steal any of it for this project :-)
