### ISSUE TITLE
flatpak-pip-generator fails on outdated==0.2.1

### ISSUE THREAD

**Issue by jwillikers** [flatpak/flatpak-builder-tools#215]
Using `flatpak-pip-generator` to generate packages fails for the package `outdated` using the latest version, 0.2.1, as there's no source package available.
I've opened alexmojaki/outdated#10 upstream to get this corrected.
Is there a simple way to workaround this or should I just build the package from source directly?

**Comment by TingPing** [comment]
There isn't a flag to use `whl` files atm.

**Comment by jwillikers** [comment]
Fixed upstream.
