### ISSUE TITLE
pip-generator fails if dependancy is only avaliable as a wheel.

### ISSUE THREAD

**Issue by Lunarequest** [flatpak/flatpak-builder-tools#219]
`mozregression` has `mozlog-7.1.0` as a dependency. looking through https://pypi.org/pypi/mozlog/7.1.0/json mozlog's 7.1.0 release  only has one file and that is the wheel. the generator will always fail here. not sure why a source dep is a requirement since a wheel should be enough and bdist will produce a wheel file in the end

**Comment by hfiguiere** [comment]
Fixed with #238 

(can't close the issue though)
