### ISSUE TITLE
/ in depandancy name breaks depandancy resolution 

### ISSUE THREAD

**Issue by advaithm** [flatpak/flatpak-builder-tools#222]
I'm currently trying to flatpak [ModernDeck](https://github.com/dangeredwolf/ModernDeck) however @sentry/browser and @sentry/tracing aren't saved properly. all other deps are found by npm but these do not, any ideas on how to fix it?

**Comment by refi64** [comment]
Whoops, turns out I fixed this months ago in #191 and forgot to merge it :sweat_smile: please try again with the latest changes!

**Comment by advaithm** [comment]
Can confirm this works. Thanks for the quick fix
