### ISSUE TITLE
[node] can't build anymore: `cache mode is 'only-if-cached' but no cached response available.`

### ISSUE THREAD

**Issue by aunetx** [flatpak/flatpak-builder-tools#244]
Hello and thank you very much for this repo,

I own the repository https://github.com/aunetx/deezer-linux, and try to (re)-build my package.
Nearly nothing has changed since last build, but I now get an error from flatpak builder when using `make export_flatpak`:

```js
========================================================================
Building module deezer in /home/aunetx/Projets/deezer-linux/flatpak/flatpak-builder/build/deezer-2
========================================================================
Running: npm install --offline
npm info it worked if it ends with ok
npm info using npm@6.14.15
npm info using node@v14.18.1
npm info lifecycle deezer-desktop@5.30.100~preinstall: deezer-desktop@5.30.100
npm timing stage:loadCurrentTree Completed in 632ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 10ms
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1304ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 2486ms
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/@types%2fsemver failed: cache mode is 'only-if-cached' but no cached response available.
npm timing npm Completed in 4294ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/deezer/flatpak-node/npm-cache/_logs/2021-11-15T12_49_52_782Z-debug.log
Error: module deezer: Le processus fils s’est terminé avec le code 1
make: *** [Makefile:52 : export_flatpak] Erreur 1
```

It looks like some packages are not cached correctly anymore (`@types/semver` here, but I don't know if it is the only one since I can't get past it).

I don't know what causes it, it is really pretty hard to get a lot of informations to fix this (especially since the app is extracted from an asar source, the package.json file is changed to include `electron` and `electron-builder`, and then it is rebuilt using flatpak... so all I know is that the package is not cached, I don't even know if it changed since last time it worked).

The content of `/run/build/deezer/flatpak-node/npm-cache/_logs/2021-11-15T12_49_52_782Z-debug.log` is [in this pastebin](https://paste.gnome.org/plxliu5vi).

If there is a way to fix this, this would be perfect; it looks like #182 but I'm not sure if it is related to git dependencies too.

Thanks a lot,
Aurélien Hamy

**Comment by gasinvein** [comment]
This is not an answer to the exact issue, but since you're generating the lockfile yourself anyway, consider using Yarn instead. It is by far less problematic for offline builds.

**Comment by aunetx** [comment]
Ok thanks a lot! I will try to use it and update here

**Comment by aunetx** [comment]
Thanks a lot, using yarn fixed everything (and even some little more)!
