### ISSUE TITLE
[npm] KeyError on npm-shrinkwrap.json from resin-io/etcher

### ISSUE THREAD

**Issue by ghisvail** [flatpak/flatpak-builder-tools#27]
I am trying to generate the sources for [io.resin.etcher](https://github.com/resin-io/etcher). The project only publishes a `npm-shrinkwrap.json` file as the manifest, and calling `flatpak-npm-generator` fails with the following error:

```sh
$ ./flatpak-npm-generator.py ../../etcher/npm-shrinkwrap.json -o ../../flathub/generated-sources.json
Scanning "../../etcher/npm-shrinkwrap.json" 
Traceback (most recent call last):
  File "./flatpak-npm-generator.py", line 228, in <module>
    main()
  File "./flatpak-npm-generator.py", line 208, in main
    s = getModuleSources(root, None, seen, include_devel=include_devel, npm3=npm3)
  File "./flatpak-npm-generator.py", line 164, in getModuleSources
    child_sources = getModuleSources(deps[dep], seen, include_devel=include_devel)
  File "./flatpak-npm-generator.py", line 96, in getModuleSources
    integrity = module["integrity"]
KeyError: 'integrity'
```

**Comment by ghisvail** [comment]
The issue may be that their `npm-shrinkwrap.json` file is using `lockfileVersion 0`, not `lockfileVersion 1`.

**Comment by nedrichards** [comment]
It looks like this isn't true any more (e.g. they now use version 1) and our tools have overall got more mature. Is this still an issue?

**Comment by ghisvail** [comment]
This is no longer an issue, indeed. Etcher cannot be built from source yet,
but for other reasons now.

Le jeu. 30 mai 2019 à 15:52, Nick Richards <notifications@github.com> a
écrit :
