### ISSUE TITLE
Why PyQt packages are not supported?

### ISSUE THREAD

**Issue by HenriWahl** [flatpak/flatpak-builder-tools#280]
Hi there,

In https://github.com/flatpak/flatpak-builder-tools/blob/d20cdd501bba3c49adc9840004ce984740d1aeed/pip/flatpak-pip-generator#L171 there is stated that no PyQt packages are supported - why?

Any chance to get support for PyQt6?

Regards

**Comment by hfiguiere** [comment]
the question is more why doesn't pyqt5 support standard python build process.

**Comment by hfiguiere** [comment]
However you can also try this:

https://github.com/flathub/com.riverbankcomputing.PyQt.BaseApp

or there are plenty of app on flathub that build pyqt5.

**Comment by HenriWahl** [comment]
OK thanks.
