### ISSUE TITLE
Change "pip3 install" to "python3.X -mpip install"

### ISSUE THREAD

**Issue by kevinsmia1939** [flatpak/flatpak-builder-tools#286]
### flatpak-builder version

1.2.2

### Linux distribution and version

openSUSE Tumbleweed

### Affected flatpak-builder tool

pip/flatpak-pip-generator

### Description

Change `pip3 install` to `python3.X -mpip install`.

I was recommend to use python3 -mpip install instead.
Would this be beneficial for flatpak purpose?
https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by TingPing** [comment]
Do you have a real bug or are you just sharing a blog post?

**Comment by kevinsmia1939** [comment]
Using `pthon3 -mpip` specify specific python intepreter.
This is a suggestion.

**Comment by TingPing** [comment]
I don't think thats a real problem for Flatpak users. Python is in the runtime and if you bundle your own version you install your bundle into `PATH` anyway.

If somebody needs to have multiple versions at one time they can contribute that feature.
