### ISSUE TITLE
npm package with multiple downloaded versions isn't recognized by npm offline.

### ISSUE THREAD

**Issue by dennisrijsdijk** [flatpak/flatpak-builder-tools#288]
### flatpak-builder version

1.2.2

### Linux distribution and version

Linux archlinux 5.18.1-arch1-1

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### flatpak-builder tool cli args

--xdg-layout ../package-lock.json

### Source repository URL

https://github.com/dennisrijsdijk/spinshare-client.git

### Flatpak-builder manifest URL

https://github.com/dennisrijsdijk/spinshare-client/blob/flatpak/flatpak/re.spinsha.Client.yml

### Description

Note: When generating a package-lock with `npm install`, you may need to provide `--legacy-peer-deps`  on newer versions of npm.  Flatpak related files are on the `flatpak` branch, under the `flatpak` directory.

When building the application with `flatpak-builder build re.spinsha.Client.yml --install --force-clean --user` it throws the following error:

```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz failed: cache mode is 'only-if-cached' but no cached response available.
npm timing npm Completed in 11655ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/electron-sample-app/flatpak-node/npm-cache/_logs/2022-06-06T15_46_44_733Z-debug.log
Error: module spinshare-client: Child process exited with code 1
```

The `color-name` package with version `1.1.3` is present in the generated-sources.json file, alongside version `1.1.4` which is a dependency of another package. I believe `1.1.4` may be replacing `1.1.3` fully, resulting in this error.

**Comment by gasinvein** [comment]
The app you've linked seems to use Yarn. Why you're generating sources (and building with) NPM?

**Comment by dennisrijsdijk** [comment]
The original developers have npm in their instructions, so I followed that. I will retry with yarn and see if that works.

**Comment by gasinvein** [comment]
There is no `package-lock.json` in the source repo. I suppose you've generated it yourself? If so, should've copied it to the flatpak build; `npm` without a lockfile will always hit network.

**Comment by dennisrijsdijk** [comment]
I would assume that's not the issue at hand here, I used the python script to generate the cache, and it seems like other packages do get installed properly before it gets to color-name.

**Comment by gasinvein** [comment]
Ugh, looks like you forgot to change the `build-options.env` according to your app. Its has `/run/build/electron-sample-app` instead of `/run/build/spinshare-client`.
