### ISSUE TITLE
flatpak-dub-generator does not pass flatpak-builder-lint

### ISSUE THREAD

**Issue by Mailaender** [flatpak/flatpak-builder-tools#329]
### flatpak-builder version

1.2.2

### Linux distribution and version

Arch Linux

### Affected flatpak-builder tool

dub/flatpak-dub-generator.py

### flatpak-builder tool cli args

./flatpak-dub-generator.py .flatpak-builder/build/lix-1/dub.selections.json -o generated-sources.json

### Source repository URL

https://github.com/SimonN/LixD.git

### Flatpak-builder manifest URL

https://github.com/flathub/com.lixgame.Lix.git

### Description

https://github.com/flathub/flatpak-builder-lint/issues/58#issuecomment-1281546017

**Comment by gasinvein** [comment]
Please try `flatpak-dub-generator.py` from #330
