### ISSUE TITLE
`linux-64` wrong mention in generated node sources

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak-builder-tools#334]
### flatpak-builder version

1.2.3

### Linux distribution and version

Fedora 37

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

After running `flatpak-node-generator npm package-lock.json` against this [package-lock.json](https://github.com/flatpak/flatpak-builder-tools/files/10203150/package-lock.json.txt), the `generated-sources.json` will contain references to a `linux-64` package, which doesn't exist on servers.

Upstream app:
https://github.com/neil-morrison44/pocket-sync

Using git commit 33e4e624692e9f993bf7882792354a6eb4cc3b4d

Removing those references as per the patch makes the build work. I have no idea where the `linux-64` thing comes from...
```
diff --git a/node-sources.json b/node-sources.json
index bf8f923..a68eb32 100644
--- a/node-sources.json
+++ b/node-sources.json
@@ -9,16 +9,6 @@
             "i386"
         ]
     },  
-    {
-        "type": "archive",
-        "url": "https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.16.3.tgz",
-        "strip-components": 1,
-        "sha256": "c8d3eae160a892e32837db3dcae515e843e5383fef52b8141940c8bcf8b6d59f",
-        "dest": "flatpak-node/cache/esbuild/.package/esbuild-linux-64@0.16.3",
-        "only-arches": [
-            "x86_64"
-        ]
-    },
     {   
         "type": "archive",
         "url": "https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.16.3.tgz",
@@ -10822,18 +10812,6 @@
             "i386"
         ]
     },  
-    {
-        "type": "shell",
-        "commands": [
-            "mkdir -p \"bin\"",
-            "cp \".package/esbuild-linux-64@0.16.3/bin/esbuild\" \"bin/esbuild-linux-64@0.16.3\"",
-            "ln -sf \"esbuild-linux-64@0.16.3\" \"bin/esbuild-current\""
-        ],
-        "dest": "flatpak-node/cache/esbuild",
-        "only-arches": [
-            "x86_64"
-        ]
-    },
     {   
         "type": "shell",
         "commands": [
```

**Comment by gasinvein** [comment]
Interesting. The extra esbuild binary package addition is most likely caused by #184. But I'm not sure why it's not needed anymore. Probably in some version they stopped pulling the arch-dependent package via postinstall script and just include it in the lockfile like a normal dependency?

**Comment by gasinvein** [comment]
@hadess Please try the tool from #335 and tell if it fixes the issue for you.

**Comment by hadess** [comment]
> @hadess Please try the tool from #335 and tell if it fixes the issue for you.

Commented there, and it does work, thanks!
