### ISSUE TITLE
Build fails with generated-sources.json created from NPM 9.x lock files (ERR! code ENOTCACHED)

### ISSUE THREAD

**Issue by jarek-foksa** [flatpak/flatpak-builder-tools#339]
### flatpak-builder version

GitHub master from 2022-12-30

### Linux distribution and version

macOS 12.6.2 (Darwin 21.6.0)

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### flatpak-builder tool cli args

-r -o ./flatpak/generated-sources.json npm ./app/package-lock.json

### Flatpak-builder manifest URL

https://github.com/flathub/com.boxy_svg.BoxySVG/blob/master/com.boxy_svg.BoxySVG.yaml

### Description

I'm using the following command to create `generated-source.json` file from `package-lock.json` files:

```
flatpak-node-generator -r -o ./flatpak/generated-sources.json npm ./app/package-lock.json
```

This used to work fine until I updated NPM from version 8.19.3 to version 9.2.0 and I recreated the lock files with it. With the new lock files, `flatpak-node-generator` is now creating a significantly smaller `generatated-source.json` which in turn [causes the build to fail](https://buildbot.flathub.org/#/builders/19/builds/1758/steps/8/logs/stdio) with following error:
```
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/electron failed: cache mode is 'only-if-cached' but no cached response available.
```

- Before (NPM 8.19.3): [generated-sources.json](https://github.com/flathub/com.boxy_svg.BoxySVG/blob/2dcce88c338038de7d1fce8d70bb180e3c4de3a2/generated-sources.json)
- After (NPM 9.2.0): [generated-sources.json](https://github.com/flathub/com.boxy_svg.BoxySVG/blob/5491912ca51c9755315035544e98541c26d6b520/generated-sources.json)

**Comment by gasinvein** [comment]
Where does the `package-lock.json` you're using to generate the sources come from? The zip archive specified in the linked manifest doesn't seem to contain one.

**Comment by jarek-foksa** [comment]
[Here](https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com/o/linux%2Fapp-npm-v8.zip?alt=media&token=71cba23f-5fbb-46c8-b349-4389d83aca3b) is the zip archive containing `package-lock.json` generated using NPM v8.19.3 and [here](https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com/o/linux%2Fapp-npm-v9.zip?alt=media&token=6e8172e8-b9db-4726-974f-a2583bf06452) is the archive with `package-lock.json` generated  using NPM v9.2.0.

Please note that there is also a second `package-lock.json` in each archive inside the `electron/` directory (that's why I was using the `-r` option when creating`generated-sources.json` ).

**Comment by jarek-foksa** [comment]
I used the command `npm install --package-lock-only --ignore-scripts` to generate the `package-lock.json` files. Perhaps there is an option in NPM 9.x to use the old package lock format?

**Comment by gasinvein** [comment]
Note that `package-lock.json` must exactly match `generated-sources.json`, and must be present during flatpak build. Trying to build a flatpak from sources without a `package-lock.json` isn't going to work.
Including `package-lock.json` in your app sources is common practice, regardless of flatpak use.

**Comment by jarek-foksa** [comment]
Thanks, adding `pacakge-lock.json` to [the zip archive](https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com/o/linux%2Fapp-3.95.4.zip?alt=media) fixed the problem ([build log](https://buildbot.flathub.org/#/builders/19/builds/1971)).
