### ISSUE TITLE
cargo generator doesn't include ``.workspace`` versions

### ISSUE THREAD

**Issue by ImUrX** [flatpak/flatpak-builder-tools#348]
### flatpak-builder version

1.2.3

### Linux distribution and version

NixOS 23.05

### Affected flatpak-builder tool

cargo/flatpak-cargo-generator.py

### Source repository URL

https://github.com/tauri-apps/plugins-workspace/blob/dev/plugins/window-state/Cargo.toml

### Flatpak-builder manifest URL

https://github.com/flathub/dev.slimevr.SlimeVR

### Description

When trying to build a git dependency that is inside a workspace, cargo can take into account the root of the workspace for versions. The generator doesnt take that into account.

**Comment by gasinvein** [comment]
This doesn't seem to work with `cargo vendor` either; since the sources generator aims to replicate Cargo's native vendoring mechanism, I'm not sure if there is a way we can make this work.

You can test if vendoring is possible for your project like this:
```bash
mkdir .cargo
cargo vendor --locked --versioned-dirs > .cargo/config
cargo build --offline
```
