### ISSUE TITLE
@electron/get > v2.0.3 requires SHA256SUMS.txt for cached files

### ISSUE THREAD

**Issue by kanru** [flatpak/flatpak-builder-tools#370]
### flatpak-builder version

1.3.3

### Linux distribution and version

Fedora Linux 38.20230903.0 (Silverblue)

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

`@electron/get` introduced a change to check the checksum file for cached files (https://github.com/electron/get/pull/212).
It looks for the checksum file at  `$XDG_CACHE_HOME/electron/$URL_HASH/SHA256SUMS.txt`

I think this is where the symlinks can be added

https://github.com/flatpak/flatpak-builder-tools/blob/de56f4702638739f930f4afa648686f12ac4d724/node/flatpak_node_generator/providers/special.py#L79-L85

I manually added the symlinks for https://github.com/flathub/com.logseq.Logseq/pull/93 and the build succeeded.

**Comment by refi64** [comment]
When you mentioned in the OG thread:

> The underlying error is reported by `electron-forge`. So I guess It was related to an electron(or its deps) upgrade.
The primary diff related to electron is `@electron/get` and `@electron/universal`.

could you share how exactly you traced it to `@electron/get`? I think I have a fix for this, but I'm having a bit of trouble repro-ing the issue, and I can't figure out the link between `@electron/get` and `@electron/universal`.

**Comment by kanru** [comment]
I think they traced it back to electron/get because it was the only relevant change in the dependencies. From the log it failed at the electron-forge packaging time and iirc electron/get was in the stack trace.

You can check the change I manually added to the manifest.

**Comment by daviddavo** [comment]
Every time we generate a new generated-sources.json, we have to manually add the link to the SHA256SUM.txt file, like in this commit:

https://github.com/flathub/com.logseq.Logseq/pull/99/commits/26647098ccaa286f8720d7ffa2f8deec00451459
