### ISSUE TITLE
npm-generator: url content data makes flatpak-builder crash

### ISSUE THREAD

**Issue by bbhtt** [flatpak/flatpak-builder-tools#372]
### flatpak-builder version

flatpak-builder-1.3.3

### Linux distribution and version

Fedra 39

### Affected flatpak-builder tool

npm/flatpak-npm-generator.py

### Source repository URL

https://github.com/endlessm/hatch-previewer

### Flatpak-builder manifest URL

https://github.com/flathub/com.endlessm.HatchPreviewer

### Description

npm generator generates this:

```
{
      "dest": "npm-cache",
      "dest-filename": "SHASUMS256.txt-2.0.8",
      "type": "file",
      "url": "data:a737902009baa7bb317485ab6c719c755c0e4b1daf3352e80b9a0dd23d683433%20%2Aelectron-v2.0.8-linux-ia32.zip%0Ac416eccf6e79fdc4df47005b4bf3d3f7c95f4bed049412ce63b9181294d020bb%20%2Aelectron-v2.0.8-linux-x64.zip%0A05bb6c331e43468a0c80cf6ee5ebe1892ef3d763713b0f7f45fe0db3fb9924aa%20%2Aelectron-v2.0.8-linux-armv7l.zip%0A68d0aa855fb4bc0e51ce4b3a5cff7bf432004d85133b4c69ded8746d53cf5c95%20%2Aelectron-v2.0.8-linux-arm64.zip%0A"
}
```

which makes builder crash:

```
(flatpak-builder:49654): GLib-CRITICAL **: 09:34:21.332: g_propagate_error: assertion 'src != NULL' failed
Error: module test: URL rejected: Port number was not a decimal number between 0 and 65535
```

```
warning: Section `.reg-xstate/19484' in core file too small.
#0  0x00007ff049d97b8f in g_log_structured_array () from /lib64/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7ff048688940 (LWP 19484))]
(gdb) bt
#0  0x00007ff049d97b8f in g_log_structured_array () at /lib64/libglib-2.0.so.0
#1  0x00007ff049d97e7c in g_log_default_handler () at /lib64/libglib-2.0.so.0
#2  0x00007ff049d98120 in g_logv () at /lib64/libglib-2.0.so.0
#3  0x00007ff049d98403 in g_log () at /lib64/libglib-2.0.so.0
#4  0x0000558a77d05895 in builder_manifest_deserialize_property
    (serializable=<optimized out>, property_name=<optimized out>, value=0x7ffdb22cef60, pspec=<optimized out>, property_node=<optimized out>)
    at ../src/builder-manifest.c:1255
#5  0x00007ff049aecc06 in json_gobject_new (gtype=Python Exception <class 'gdb.error'>: No type named TypeNode.
, object=0x7ff034000cc0) at ../json-glib/json-gobject.c:296
#6  0x00007ff049aecdc8 in json_gobject_deserialize (gtype=<optimized out>, node=<optimized out>) at ../json-glib/json-gobject.c:805
#7  0x0000558a77d23734 in builder_gobject_from_data (gtype=Python Exception <class 'gdb.error'>: No type named TypeNode.
, relpath=<optimized out>, contents=<optimized out>, error=0x7ffdb22cf120)
    at ../src/builder-utils.c:542
#8  0x0000558a77cf1d2f in main (argc=<optimized out>, argv=<optimized out>) at ../src/builder-manifest.c:120
```

**Comment by gasinvein** [comment]
flatpak-npm-generator (along with flatpak-yarn-generator) is long since obsolete, you should use flatpak-node-generator instead.

**Comment by bbhtt** [comment]
> flatpak-npm-generator (along with flatpak-yarn-generator) is long since obsolete, you should use flatpak-node-generator instead.

Yea I used node generator for this app but it fails for another #373 leaving me no choice.

**Comment by hfiguiere** [comment]
> flatpak-npm-generator (along with flatpak-yarn-generator) is long since obsolete, you should use flatpak-node-generator instead.

so it should be removed then.

**Comment by gasinvein** [comment]
> > flatpak-npm-generator (along with flatpak-yarn-generator) is long since obsolete, you should use flatpak-node-generator instead.
> 
> so it should be removed then.

It was userful for some ancient npm versions which I believe aren't used anywhere nowadays, so I agree we should just remove the old npm and yarn generators.

**Comment by refi64** [comment]
It barely even worked on the old versions, the origin story of node-generator was basically me trying and failing to get them to work and then cursing and starting a new generator.

**Comment by bbhtt** [comment]
Builder is introducing support for data URIs back in https://github.com/flatpak/flatpak-builder/pull/563

**Comment by bbhtt** [comment]
Closing as above is merged
