### ISSUE TITLE
Rust (Cargo) support

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/flatpak-builder-tools#39]
It would be nice to have Rust (Cargo) support! this would allow an easier build for Fractal/Podcasts in gnome-apps-nightly.

**Comment by alatiera** [comment]
For anyone interested, there's already a script we use with Buildstream that parses `Cargo.lock` and generates yaml [here][1]. It shouldn't be too hard to adapt it to write json instead. 

[1]: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/utils/generate_cargo_dependencies.py
