### ISSUE TITLE
Node generator don't create symlink to SHASUMS256.txt, electron/get gets cache miss

### ISSUE THREAD

**Issue by L11R** [flatpak/flatpak-builder-tools#403]
### flatpak-builder version

1.4.2

### Linux distribution and version

Arch Linux

### Affected flatpak-builder tool

node/flatpak-node-generator.py

### Description

I am using @electron/forge (not electron-builder). I got it work, but manually patched `special.py` with this:

```python
self.gen.add_shell_source(
    [
        f'mkdir -p "{sanitized_url}"',
        f'ln -s "../{binary.filename}" "{sanitized_url}/{binary.filename}"',
        f'mkdir -p "{url_hash}"',
        f'ln -s "../{binary.filename}" "{url_hash}/{binary.filename}"',
        f'mkdir -p "{url_hash}"', 
        f'ln -s "../SHASUMS256.txt-29.1.0" "{url_hash}/SHASUMS256.txt"',
    ],
    destination=electron_cache_dir,
    only_arches=[binary.arch.flatpak],
)
```

Otherwise electron/get cannot find SHASUMS256.txt, tries to download it and fails.

**Comment by hfiguiere** [comment]
since you have a patch maybe you can submit a PR for it.

**Comment by L11R** [comment]
@hfiguiere I am not fluent in Python and don't know how to properly pass `SHASUM256.txt` version. Patch above should be manually fixed for each Electron version.

**Comment by refi64** [comment]
I think this is fixed by #376?

**Comment by L11R** [comment]
Yeah! I missed that PR, digged this issue myself...

**Comment by refi64** [comment]
PR is merged.
