### ISSUE TITLE
manifest from flatpak-pip-generator fails to build python3-pdftotext

### ISSUE THREAD

**Issue by asubedi** [flatpak/flatpak-builder-tools#54]
I generated the manifest for pdftotext and copied it to the manifest for an application that I am developing with Gnome Builder.  Building the project with Gnome Builder fails with the error

`     pdftotext.cpp:3:10: fatal error: poppler/cpp/poppler-document.h: No such file or directory
     #include <poppler/cpp/poppler-document.h>
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.`

How would I get it to build and install poppler-cpp files?

**Comment by asubedi** [comment]
Well, adding the following snippet that I found in the internets worked. 
`
            {
   	    "name": "poppler",
            "buildsystem": "cmake-ninja",
            "config-opts": [
                "-DCMAKE_INSTALL_LIBDIR=/app/lib",
                "-DCMAKE_INSTALL_INCLUDEDIR=/app/include",
                "-DENABLE_LIBOPENJPEG=none"
            ],
            "cleanup": [
                "/bin"
            ],
            "sources": [
                {
                    "type": "archive",
                    "url": "https://poppler.freedesktop.org/poppler-0.69.0.tar.xz",
                    "sha256": "637ff943f805f304ff1da77ba2e7f1cbd675f474941fd8ae1e0fc01a5b45a3f9"
                }
            ]
		}
`
(Sorry can't get it to add the newline in the "insert code" mode.)

However, it would still be nice to get it working entirely with flatpak-pip-generator.

**Comment by barthalion** [comment]
I don't think it's feasible to make it generate modules for external dependencies, just as it pip itself doesn't install them.
