### ISSUE TITLE
[pip] Error on PyPi packages stored in zip file

### ISSUE THREAD

**Issue by robozman** [flatpak/flatpak-builder-tools#70]
`flatpik-pip-generator` throws an error when pulling a dependency that is stored in a zip file.
```
Traceback (most recent call last):
  File "./flatpak-builder-tools/pip/flatpak-pip-generator", line 139, in <module>
    name = get_package_name(filename)
  File "./flatpak-builder-tools/pip/flatpak-pip-generator", line 58, in get_package_name
    'Downloaded filename: {} does not end with gz or whl'.format(filename)
Exception: Downloaded filename: setuptools-41.2.0.zip does not end with gz or whl
```
Current solution is to run a
```
sed -i "s/filename.endswith('gz')/filename.endswith('gz') or filename.endswith('zip')/g" flatpak-builder-tools/pip/flatpak-pip-generator
```
on the script before running it.  In this case, the  setuptools dependency is never even built as it is provided by the `org.gnome.Platform` environment.

Thanks

**Comment by barthalion** [comment]
That was fixed via https://github.com/flatpak/flatpak-builder-tools/commit/4c795950ff99fd0db2755da49267eeb3f38de5e5
