### ISSUE TITLE
[cargo] provide an example

### ISSUE THREAD

**Issue by gdesmott** [flatpak/flatpak-builder-tools#71]
I didn't manage to make an offline build using the cargo generator. Would be good to provide an example as the one we have for node.

**Comment by muelli** [comment]
FTR: here is a manifest that makes use of the cargo generator: https://github.com/flathub/chat.delta.desktop/blob/1b9aeb3b1909b0cd31e4614fcbdda32fbbc6869c/deltachat-core-rust.yaml
