### ISSUE TITLE
[cargo] git+https urls seem to be unsupported

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak-builder-tools#72]
This seems to be similar to https://github.com/flatpak/flatpak-builder-tools/issues/66

I want to run the tool on [this Cargo.lock file](https://github.com/deltachat/deltachat-core-rust/blob/e251c7b1c825929f69125b6436fe51ed8fe56dc2/Cargo.lock). The interesting bit is this: https://github.com/deltachat/deltachat-core-rust/blob/e251c7b1c825929f69125b6436fe51ed8fe56dc2/Cargo.lock#L499

The generated-sources.json does not contain the module and building the package fails:

```
    Updating git repository `https://github.com/jonhoo/rust-imap`
warning: spurious network error (2 tries remaining): curl error: Could not resolve host: github.com
; class=Net (12)
warning: spurious network error (1 tries remaining): curl error: Could not resolve host: github.com
; class=Net (12)
error: failed to load source for a dependency on `imap`
```

It would be good if the generator dealt with git urls.

**Comment by muelli** [comment]
I've dug a bit into the cargo space.

A git directory seems to be stored in `cargo/git/db/$name-$hash` as per https://github.com/rust-lang/cargo/blob/master/src/cargo/sources/git/source.rs#L72 and https://github.com/rust-lang/cargo/blob/d5d7557cf5ba2993cab572076753db73091a5b7f/src/cargo/sources/git/source.rs#L118


The [short_hash](https://github.com/rust-lang/cargo/blob/d5d7557cf5ba2993cab572076753db73091a5b7f/src/cargo/sources/git/source.rs#L12) is a siphash and the canonical url is the massaged repository's URL, e.g. https://github.com/jonhoo/rust-imap (that I found by building cargo myself and checking what it passes to the hash).

One complication is the generation of the hash. The magic ingredient is Rust appending 0xff to every string, cf. https://doc.rust-lang.org/src/core/hash/mod.rs.html#611-616.
With that knowledge, we can generate the hash, too. I will play around with [my version](https://github.com/muelli/flatpak-builder-tools/commit/72e32b6c0163b002c282965132e0fdad43b0d20d) for a while and then propose the patch.

**Comment by gdesmott** [comment]
I'm also having troubles with `git+https` but encounter a different error message.

My `Cargo.lock` contains
```
[[package]]
name = "gst-plugin-cdg"
version = "0.5.2"
source = "git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs?branch=0.5#8ce4ca65123f0911819af491e7073449378eb501"
```

which is converted in the generated file to:

```
    {
        "type": "git",
        "url": "git+https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs",
        "commit": "8ce4ca65123f0911819af491e7073449378eb501",
        "dest": "cargo/vendor/gst-plugin-cdg"
    },
```

But when trying building the manifest I get:
```
Downloading sources
Initialized empty Git repository in /home/cassidy/dev/rust/karapulse/.flatpak-builder/git/git+https_gitlab.freedesktop.org_gstreamer_gst-plugins-rs-CUQFE0/
fatal: unable to find remote helper for 'git+https'
Failed to download sources: module karapulse: Child process exited with code 128
```

Looks like `git` doesn't like the `git+https://` url.

**Comment by muelli** [comment]
that's weird, because it seems to work fine enough for me: https://github.com/deltachat/deltachat-core-rust/blob/d83652b0fcdf6cf4a9b8b66755ce9acb687b4bc1/Cargo.lock#L790-L793

That builds with https://github.com/flathub/chat.delta.desktop/blob/1b9aeb3b1909b0cd31e4614fcbdda32fbbc6869c/deltachat-core-rust.yaml

Do you have a manifest that doesn't work as expected to share? Then I might be able to take a closer look.

**Comment by gdesmott** [comment]
You can test with this branch: https://gitlab.freedesktop.org/gdesmott/karapulse/tree/cargo-vendor

The generated file is `build-aux/cargo-generated-sources.json` and you can try building with `flatpak-builder build-dir build-aux/org.karapulse.KarapulseDevel.json`

Thanks!

**Comment by muelli** [comment]
check out https://github.com/flatpak/flatpak-builder-tools/pull/91 and https://gitlab.freedesktop.org/muelli/karapulse/commit/894241645a18e082dbac6fc632817af79e2f7617

**Comment by gdesmott** [comment]
Great, I'll check that out. Thank you so much!

**Comment by gdesmott** [comment]
@muelli : why did you add `--share=network`. Shouldn't we be able to do a full offline build?

**Comment by gdesmott** [comment]
I managed to make it all work, thank you so much for your help! :+1:

**Comment by muelli** [comment]
so I guess we can close this bug for now as the generator has some fixes for the issues we encountered.
